### ISSUE TITLE
Disallow user from unchecking language if it has values in form

### ISSUE THREAD

**Issue by tituomin** [City-of-Helsinki/linkedevents-ui#106]
Inform user that there are already values entered for example in English, when trying to uncheck "english" in HelLanguageSelect.

**Comment by Rikuoja** [comment]
Well, actually currently this is implemented so that the language can be unchecked, but the values remain in the field until the event is submitted.

Is it okay that the user may uncheck a language, and then save the event, deleting the texts in unchecked languages @aleksisalonen ? This is related to https://github.com/City-of-Helsinki/linkedevents-ui/issues/309 which I just closed.

If it's not okay, then I think we will have to prevent unchecking, so the user may not delete the data just by unchecking and sending the event?

**Comment by aleksisalonen** [comment]
I suppose this is a matter of taste, but I think the current solution is user friendly enough.

**Comment by Rikuoja** [comment]
Yeah, I agree that it makes it quite obvious to the user that if they deselect a language and then save the changes, the data is actually lost.
