### ISSUE TITLE
Switch to event-endpoint in UI search

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#174]
Switch to using the event-endpoint instead of the search-endpoint on the UI search page. Retain abbility to limit search wit start and end dates.

**Comment by Rikuoja** [comment]
The search endpoint doesn't support sorting due to ES shenaningans.

Just transition to using the event endpoint, where text search seems to have sufficient performance:`https://api.hel.fi/linkedevents/v1/event/?start=today&sort=start_time&text=savoy`

This also means we should automatically fill in the dates on the form so that start date is today and the end date is blank.

**Comment by Rikuoja** [comment]
Also, this will allow for a sorting control in the search view in the future if we wish the user to have that.

**Comment by Rikuoja** [comment]
Also, using the event endpoint will fix the related issue #244 without further coding!

**Comment by aleksisalonen** [comment]
Done.
