### ISSUE TITLE
Add automatic messaging functionality for moderation-related operations

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#243]
To work in conjunction with issue #242.

The UI should be able to initiate the sending of automatic email messages based on the actions of a moderator and the actions of regular users posting drafts.

There are three types of messages to be sent:
1. If a moderator deletes an unpublished event, an automatic email (containing message 1) should be sent to the email address of the submitter.
2. If a moderator publishes an unpublished event, an automatic email (containing message 2) should be sent to the email address of the submitter.
3. If a draft is posted by a regular user, an automatic email (containing message 3) should be sent to the email address(es) of the admin users of the organization in question.

The messages should be sent for individual events that don't have a superevent and superevents, but not for subevents that have a superevent.

The solution should be done using the Mailgun-API, ask tech lead / Ville K. for more details.

**Comment by Rikuoja** [comment]
Well. Since calling the mailgun API requires an API key, the calling instance will have to be our server which has the secret key.

That means that this issue is a backend issue, should be written in https://github.com/City-of-Helsinki/linkedevents/issues instead. The backend handles user rights and contains the user database anyway.

**Comment by Rikuoja** [comment]
Added the backend issue https://github.com/City-of-Helsinki/linkedevents/issues/333
