### ISSUE TITLE
Group subevents under superevents in Tapahtumien hallinta

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#259]
Subevents and their related superevents should be grouped together. Display all subevents under their corresponding superevent.

Superevents should be graphically distinguishable (bold, and marked with green tag SARJA) from subevents, and subevents should be marked with an indentation vis-à-vis the superevent.

Let's hide the subevents by default and load + unfold them on user click only. Add a downward arrow next to the super event name for unfolding the indented subevent list.

**Comment by Rikuoja** [comment]
This can be implemented either

1) in the UI, fetching 100 or so events, and then formatting the fetched list, and possibly fetching any missing subevents from the API separately, 

*or*

2) in the backend, allowing subevents to be serialized under superevents. Then, we would always get a list of 100 superevents, with subevents inlined, and a huge json mess to boot :)

**Comment by Rikuoja** [comment]
The problem, of course, remains, of what to do with any subevents returned from the API whose superevents haven't been returned. Then we would have to separately fetch 1) superevents for subevents that are missing one, and 2) subevents for superevents that are missing any. A mess, in my opinion.

**Comment by Rikuoja** [comment]
Ah! But we can use the API `?recurring=super` when fetching the initial 100 events. Then, if the `sub_events` field is not-null, for each of those events use the just-specified `?super_event=event_id` filter to fetch all subevents for each of them.

We will get loads of events in a tree, and loads of concurrent loads, so performance will be a problem if we have loaded 100 superevents and each has 100 subevents.

Perhaps hide the subevents by default, or perhaps only load them when the user clicks an arrow opening the specific superevent branch, or what do you think @aleksisalonen ?

**Comment by Rikuoja** [comment]
We don't really want to do this in the API, because if we have 100 events and all of a sudden all of them have 100 subevents, the json will take too long for the API to generate for the UI to be responsive.

**Comment by Rikuoja** [comment]
All this is because it is not guaranteed that the API will return all subevents together.

If we want only 100 events returned, be they sub or super, then the API should have a filter that allows event ordering by superevent properties. And still we have all the problems of missing subevents, as the number of subevents in a superevent will most definitely generally be a prime (or non-prime) factor of 100.

**Comment by aleksisalonen** [comment]
Sounds like a reasonable solution, let's hide the subevents by default and load them on user click.

**Comment by Rikuoja** [comment]
Okay. The way to do this is just one call to the backend: `/v1/event/?super_event=none&publisher=...`

**Comment by Rikuoja** [comment]
We will actually know which returned events have subevents, because their ids are included in the API event.

But to get the subevent details (when the user clicks the superevent open arrow or something similar?) in the list, for each click we need an API call `/v1/event/?super_event=super_event_id` for the super event that was clicked.

**Comment by Rikuoja** [comment]
Mind you, if it is possible, it would be safest to make the component recursive. Because subevents may have subevents in the future (recurring events inside festivals).
