### ISSUE TITLE
Disallow empty string in description and short description fields

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#265]
Currently the form validation will allow for empty strings in the description (and presumably short description) field(s). 

This should be changed, so that user-added empty strings will trigger the empty field -warning.

**Comment by Rikuoja** [comment]
Agreed. In https://github.com/City-of-Helsinki/linkedevents-ui/commit/adc4bea9a92ad7db105e08d7a232b4ac079967b4 I fixed the empty strings so that they are not sent to the backend, so saving such an event will not succeed.

However, the validation should also notice that the fields have empty strings, and tell it to the user.

**Comment by Rikuoja** [comment]
@aleksisalonen is this still a problem?

Code https://github.com/City-of-Helsinki/linkedevents-ui/blob/master/src/validation/validationRules.js#L201 seems to indicate that this is already fixed.

**Comment by Rikuoja** [comment]
However, there is a caveat: if *multiple languages* are selected, then it seems that *some* of them are allowed to be empty? I believe that is the issue here.
