### ISSUE TITLE
Display images with pagination

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#316]
At the image browsing modal, images are loaded on an infinite scroll basis.

Change to pagination, with a page size of 100 images.

**Comment by Rikuoja** [comment]
Ah. It seems the number of images of Helsinki Marketing has exceeded the magic count of 1000.

As the UI doesn't know how to load more than 1000 images, is only loads the first 1000 of them and displays them.

So, pagination should be implemented in the image dialog.

In addition (and as short-term solution), the images fetched should be ordered by date added, so new images are always shown first.

**Comment by Rikuoja** [comment]
Fixed this for the short term in backend https://github.com/City-of-Helsinki/linkedevents/commit/8b44cce691fc42afcf6b901921031342568f22b0 . Ordering by `last_modified_time` was borked.

So from now on, first images will be those that were added (or metadata modified) recently.

However, I will keep this issue open, because we might want the image dialog to support loading more than a thousand images. Or do we?

**Comment by aleksisalonen** [comment]
Done.
