### ISSUE TITLE
Autocomplete fields fail at certain intervals

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#343]
The autocomplete fields for place and keywords fail to provide correct suggestions at certain intervals.

See for example the place field:

"leikkipuisto ar" → no results
"leikkipuisto ara" → correct result

For keywords:

"laps..i...p...e...r...h...e" and so on, also produce varying, inconsistent results.

or

"vauvape" → no results
"vauvaper" → correct result

**Comment by midori0507** [comment]
@aleksisalonen can you provide screenshot ?

**Comment by Rikuoja** [comment]
This might be an API issue, it seems for me the API will return text matches to different language fields in different requests. This might explain the inconsistency when doing the same searches again, reloading the form.

**Comment by Rikuoja** [comment]
Looks like UI autocomplete field

1) caches the requests already made, so they are not done again
2) filters the list so that when matches based on the wrong language are made, the results are actually not shown to the user, resulting in empty result set.

Can you verify that this is the UI behavior, @midori0507 ? I can check what is going wrong on the API side.

**Comment by Rikuoja** [comment]
This is most likely an old issue in the API. Don't know why we haven't noticed this earlier.

**Comment by Rikuoja** [comment]
Fixed now in backend commit https://github.com/City-of-Helsinki/linkedevents/commit/e973772e9480e1a8aa752424ba1bdae17b82560f
