### ISSUE TITLE
Fix double encoding of spaces in UI search

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#524]
Blank spaces in the Ui search are double encoded:

First " " → "%20", then "%" → "%2520" effectively disabling all searches with blank spaces.

Fix bug.

**Comment by Rikuoja** [comment]
Fixed in https://github.com/City-of-Helsinki/linkedevents-ui/commit/cd3c0a0da525d085269f59830a3265cd77e41442 .

Currently axios seems to encode spaces as "+", not "%20", if we don't encode the string manually, but luckily our API accepts that. A PR in the axios library should fix that in the future.
